# AWS Infra playbook
---

- hosts: localhost
  connection: local
  gather_facts: False
  #become: true
  vars_files: 
    - /home/opstree/devops-ninja/Ansible/Assignment03/aws_keys.txt
  vars:
    key_name: my_aws             # Key used for SSH
    region: ap-south-1       # Region may affect response and pricing
    image: ami-0a7cf821b91bcccbc # look in ec2 > ami (filter owner alias: amazon) or amis of manually launched instances
    id: "ansible"
    instance_type: t2.micro     # Choose instance type, check AWS for pricing
    # vpc_id: subnet-012345
    sec_group: "ansible-all-traffic"
    ansible_python_interpreter: "/usr/bin/python3"  # Replace with the correct path

  tasks:
    - name: Create security group
      amazon.aws.ec2_security_group:
        name: "{{ sec_group }}"
        description: "Sec group for Ansible EC2 infra"
        region: "{{ region }}"
        aws_access_key: "{{ec2_access_key}}"  # From vault as defined
        aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined
        rules:                                # allows ssh on port 22
          - proto: tcp
            ports:
              - 22
              - 80
              - 8080
              
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on 22 and 80 port
    - name: Amazon EC2 | Create Key Pair      # Create key pair for ssh
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
        aws_access_key: "{{ec2_access_key}}"  # From vault as defined
        aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined
        key_material: "{{ item }}"
      with_file: /home/opstree/.ssh/my_aws.pub

    - name: Create an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "ansible-nginx"
        key_name: "{{ key_name }}"
        # vpc_subnet_id: "{{ vpc_id }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ sec_group }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        region: "{{ region }}"
        network:
          assign_public_ip: true
        image_id: "{{ image }}"
      register: ec2_result  

    - name: Debug output for ec2_result.instances[0].public_ip_address
      debug:
        msg: "The instance Public IP is {{ ec2_result.instances[0].public_ip_address }}"

 


# command to use
# ansible-playbook  infra.yml --ask-vault-pass -v
