---
# vars file for haproxy

haproxy_package: "haproxy"
haproxy_service: "haproxy"
haproxy_version: "2.4.*"  # Change this to the desired version

haproxy_config_template: "haproxy.cfg.j2"
haproxy_config_dest: "/etc/haproxy/haproxy.cfg"

haproxy_listen_ports:
  - 8080
  - 443

haproxy_backend_server: 
  - 192.168.1.38:8081
  - 192.168.1.38:8082
  - 192.168.1.38:8083